version: "3"

services:
  mysql:
    image: mysql:8.0
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      --default-authentication-plugin=mysql_native_password
      --init-file /docker-entrypoint-initdb.d/init.sql  #attention here
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - "../test/database/quick_web.sql:/docker-entrypoint-initdb.d/init.sql"

  redis:
    image: 'redis:latest'
    command: redis-server --requirepass 123456
    ports:
      - '6379:6379'